### ISSUE TITLE
The file read_display_proto_file.py does not run

### ISSUE THREAD

**Issue by mathagician** [shreybatra/Flask-with-Protocol-Buffer-Serializer#12]
The logic is incorrectly coded.

Steps to reproduce

Run `python read_display_proto_file.py`

**Comment by shreybatra** [comment]
@mathagician please read point 5, 6 of Readme again.... In order for them to run you have to provide a protobuf file which has to be read.. So run it as - 
```python read_display_proto_file.py temp.pb```
This temp.pb file is created when you run
```python make_proto_file.py temp.pb```
You can give any name instead of temp.pb
